image: Visual Studio 2017
environment:
  RUST_TEST_THREADS: 1
  matrix:
    - TARGET: x86_64-pc-windows-msvc
      RUST_CHANNEL: beta
      WPD_LIB_PATH: "C:/dl/wpdpack/WpdPack/Lib/x64/Packet.lib"
      PYTHON: "C:\\Python36-x64"
      PYTHON_ARCH: "64"
      VCVARS: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\amd64\\vcvars64.bat"
install:
 - SET PATH=%PYTHON%;%path%
 - ps: mkdir C:/dl
 - curl -o "C:/dl/wpd.zip" "https://www.winpcap.org/install/bin/WpdPack_4_1_2.zip"
 - ps: Add-Type -AssemblyName system.io.compression.filesystem
 - ps: "[io.compression.zipfile]::ExtractToDirectory(\"C:/dl/wpd.zip\", \"C:/dl/wpdpack\")"
 - ps: cp ${env:WPD_LIB_PATH} "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64"
 - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-${env:RUST_CHANNEL}-${env:TARGET}.exe"
 - rust-%RUST_CHANNEL%-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
 - CALL "%VCVARS%"
 - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
 - choco install winpcap
 - rustc -V
 - cargo -V
test: false
build_script:
  - cargo build --release --verbose
after_build:
- ps: cd ${env:APPVEYOR_BUILD_FOLDER}/gui
- python -m venv env
- ps: .\env\Scripts\activate.ps1
- pip install -r requirements.txt
- ps: cd src
- ps: cp ${env:APPVEYOR_BUILD_FOLDER}\target\release\meter.dll libmeter.pyd
- pyinstaller -F -w -i ..\..\assets\albion-stats-icon.ico meter.py
- ps: deactivate
- ps: mv dist\meter.exe ..\..\albion-online-stats.exe
- ps: ls
- ps: ls ..\
artifacts:
  path: albion-online-stats.exe
  name: binary
deploy:
  provider: GitHub
  auth_token:
    secure: cB8zvJaO/tS/Z3v4038LBCsRaO9LqrtRS0CV/eLfHnG5SefWKNSObALSvphoQxC4
  artifact: binary
  draft: false
  prerelease: false
  on:
    APPVEYOR_REPO_TAG: true # deploy on tag push only
